---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user1-dev

resources:
- ./my-web-app.yaml

images:
- name: registry.access.redhat.com/ubi9/httpd-24
  newName: registry.access.redhat.com/ubi9/httpd-24
  digest: sha256:38d71a4cf177f39a2bbe745183009943dbbf404de02aa5f879694aa024a4e6ac