apiVersion: v1
kind: Service
metadata:
  name: nationalparks
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.backend.labels" . | nindent 4 }}
    # This label is read by parksmap to auto-discover backend services
    type: parksmap-backend
spec:
  type: ClusterIP
  selector:
    {{- include "parksmap.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: 8080-tcp
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
    {{- range .Values.backend.extraPorts }}
    - name: {{ printf "%d-tcp" (.containerPort | int) }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
    {{- end }}
