apiVersion: apps/v1
kind: Deployment
metadata:
  name: parksmap
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "parksmap.frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        {{- include "parksmap.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: parksmap
          image: {{ include "parksmap.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
