apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: userN-dev

resources:
  - ../../base

configMapGenerator:
  - name: web-message
    behavior: replace
    literals:
      - APP_MESSAGE=Hello from Kustomize DEV overlay
