apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: challenge4-production

resources:
  - ../../base

configMapGenerator:
  - name: web-message
    behavior: replace
    literals:
      - APP_ENV=PRODUCTION
      - ENV_COLOR=#059669
      - APP_MESSAGE=Hello from PRODUCTION environment
      - APP_SUBTITLE=Production-ready overlay deployed via Kustomize.
