---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-web-app

resources:
- ./../../bases/my-web-app/
# - ./secrets/ <-- IGNORE --- for now... dont need a pull secret, but this is where you would add it if you had one

patches:
- path: ./patches/my-web-app/psm.yaml