{{- if .Values.backend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nationalparks
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.backend.labels" . | nindent 4 }}
    type: parksmap-backend
spec:
  {{- if .Values.backend.route.host }}
  host: {{ .Values.backend.route.host }}
  {{- end }}
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: nationalparks
    weight: 100
  wildcardPolicy: None
  tls:
    termination: {{ .Values.backend.route.tls.termination }}
    {{- if .Values.backend.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.backend.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
{{- end }}
