apiVersion: v1
kind: Service
metadata:
  name: parksmap
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "parksmap.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: 8080-tcp
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
