---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-web-app-2

resources:
- ./namespace.yaml
- ./deployment.yaml


images:
- name: nginx
  newName: docker.io/library/nginx
  newTag: 1.25.3