apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.database.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-usr: {{ .Values.database.credentials.adminUser | quote }}
  admin-pwd: {{ .Values.database.credentials.adminPassword | quote }}
  app-usr: {{ .Values.database.credentials.appUser | quote }}
  app-pwd: {{ .Values.database.credentials.appPassword | quote }}
