{{- if .Values.rolebinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: {{ include "parksmap.namespace" . }}
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
roleRef:
  # Security Note: For a workshop setting, granting the generic 'view' ClusterRole
  # is expedient. In a strict production environment, you should create a minimal
  # custom Role that ONLY grants 'get' and 'list' verbs on 'services' resources.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ include "parksmap.namespace" . }}
{{- end }}
