---
# Source: betterthanbot/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-web-app-betterthanbot
  labels:
    helm.sh/chart: betterthanbot-0.0.1
    app.kubernetes.io/name: betterthanbot
    app.kubernetes.io/instance: my-web-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
spec:
  host: my-webapp.example.com
  to:
    kind: Service
    name: my-web-app-betterthanbot
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
